/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#efe6e2",
        "on-surface": "#1e1b18",
        "primary-container": "#0a261f",
        "inverse-primary": "#afcdc2",
        "tertiary-fixed": "#e6e2dd",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e9e1dc",
        "on-primary-fixed-variant": "#314c44",
        "surface-container": "#f5ece7",
        "on-secondary-fixed": "#370e00",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#042019",
        "surface-dim": "#e1d8d4",
        "inverse-surface": "#34302c",
        "surface": "#fff8f5",
        "secondary": "#8d4d32",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#1c1c19",
        "on-secondary-fixed-variant": "#71361d",
        "on-background": "#1e1b18",
        "secondary-container": "#feaa88",
        "outline": "#727975",
        "surface-tint": "#49645b",
        "on-surface-variant": "#424845",
        "on-secondary": "#ffffff",
        "on-primary-container": "#728f85",
        "on-tertiary-fixed-variant": "#484743",
        "on-secondary-container": "#783c22",
        "surface-container-low": "#fbf2ed",
        "surface-bright": "#fff8f5",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#c9c6c1",
        "surface-container-highest": "#e9e1dc",
        "tertiary-container": "#22211e",
        "primary": "#000e09",
        "tertiary": "#0b0a08",
        "on-tertiary-container": "#8a8884",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#ffb598",
        "primary-fixed": "#cbe9de",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f8efea",
        "outline-variant": "#c1c8c4",
        "primary-fixed-dim": "#afcdc2",
        "background": "#fff8f5",
        "secondary-fixed": "#ffdbce",
        // Homepage specific palette
        "oasis-cream": "#f9f3e5",
        "oasis-tan": "#e6d2b5",
        "oasis-black": "#1a1a1a",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "container-max": "1280px",
        "margin-desktop": "64px",
        "base": "8px",
        "gutter": "32px",
        "section-gap": "120px",
        "margin-mobile": "20px"
      },
      fontFamily: {
        "body-lg": ["Manrope", "sans-serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "body-md": ["Manrope", "sans-serif"],
        "display-lg": ["Playfair Display", "serif"],
        "button": ["Manrope", "sans-serif"],
        "label-caps": ["Manrope", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "display-md": ["Playfair Display", "serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "serif-custom": ["Courier Prime", "monospace"],
        "sans-custom": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["20px", { "lineHeight": "32px", "fontWeight": "400" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "26px", "fontWeight": "400" }],
        "display-lg": ["84px", { "lineHeight": "92px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "button": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "700" }],
        "headline-md": ["32px", { "lineHeight": "40px", "fontWeight": "500" }],
        "display-md": ["60px", { "lineHeight": "68px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-lg": ["48px", { "lineHeight": "56px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
